### ISSUE TITLE
Basename feature in  #3722 doesn't work after "yarn build"

### ISSUE THREAD

**Issue by meggarr** [conductor-oss/conductor#7] opened 2023-12-17 04:32 UTC
**Describe the bug**
The feature in  #3722 breaks the "NavLink" with "newTab". The package's homepage (aka basename) doesn't work after "yarn build". 

This works on v3.15.0 tag, shall we revert ?

@haricane8133

**Details**
Conductor UI on the latest main.

**To Reproduce**
1. Build and run the conductor UI
2. Goto Workflow Definitions
3. Click the "Executions" 's Query Link,
4. It doesn't work.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by haricane8133** [comment] 2023-12-17 05:47
So yarn build command doesn't respect the basename field in the package.json is it?

**Comment by haricane8133** [comment] 2023-12-17 07:02
@meggarr, could you check if this is because of https://github.com/Netflix/conductor/pull/3873?

@nhandt2021, we have the function `cleanDuplicateSlash()` right?
Do we have to remove the slash there? I think that removing that slash might have broken...
Could you check and let me know if I need to assist?

![Screenshot 2023-12-17 at 12 28 42 PM](https://github.com/conductor-oss/conductor/assets/37411837/6dd593f7-5ab5-4a0d-a4d5-aa765044220d)

**Comment by meggarr** [comment] 2023-12-17 07:28
@haricane8133 No, it's not. That's because, at runtime, there isn't `packageJson.hostname`, so that's always empty/null. So the "newTab" of NavLink fails without host name, so it fails.

**Comment by nhandt2021** [comment] 2023-12-17 07:35
@meggarr Thats right
@haricane8133 the current regex doesn't check the duplicated slash right after the host name

**Comment by haricane8133** [comment] 2023-12-17 08:23
@meggarr, react-scripts uses WebPack internally right? It is strange that it isn't bundling the JSON dependency...

@nhandt2021, I see. Maybe we have to change the comment/function name then.

**Comment by haricane8133** [comment] 2023-12-17 08:45
The `homepage` field passed in package.json is available in the final JS...

<img width="1726" alt="Screenshot 2023-12-17 at 2 14 22 PM" src="https://github.com/conductor-oss/conductor/assets/37411837/72cc97ce-9e56-4843-b22c-c7aded6446ef">

**Comment by nhandt2021** [comment] 2023-12-17 08:47
@meggarr 
cc: @haricane8133 
I've double checked again. It still works fine.

You need you run this command after building: `yarn serve-build` or `npm serve-build`

**Comment by haricane8133** [comment] 2023-12-17 09:01
> @haricane8133 the current regex doesn't check the duplicated slash right after the host name

@nhandt2021, the regex works at all places except at `://`

<img width="797" alt="Screenshot 2023-12-17 at 2 30 18 PM" src="https://github.com/conductor-oss/conductor/assets/37411837/eafdef54-83d1-44ff-a771-d3bde7f35889">

**Comment by meggarr** [comment] 2023-12-17 09:05
@nhandt2021 What about docker build, does that work ?

**Comment by nhandt2021** [comment] 2023-12-17 09:18
> > @haricane8133 the current regex doesn't check the duplicated slash right after the host name
> 
> @nhandt2021, the regex works at all places except at `://`
> 
> <img alt="Screenshot 2023-12-17 at 2 30 18 PM" width="797" src="https://private-user-images.githubusercontent.com/37411837/291051918-eafdef54-83d1-44ff-a771-d3bde7f35889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDQzNjAsIm5iZiI6MTcwMjgwNDA2MCwicGF0aCI6Ii8zNzQxMTgzNy8yOTEwNTE5MTgtZWFmZGVmNTQtODNkMS00NGZmLWE3NzEtZDNiZGU3ZjM1ODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA5MDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmRjM2JlZTBkNDk2YjRkZjY5OTcwZjY4N2ZjMGRhMmUyZDZlZWM1Yjg4YTllZmRkMzhlNjdlM2Y1ZWZkMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdT80ro7LrYoyi7W1c1tVpBiPe7vzymtttso6S11QTc">

@haricane8133  doesn't work (for below case), that's why I raised that PR 

![image](https://github.com/conductor-oss/conductor/assets/83625759/285c132f-4190-4402-b97f-d708688e2be9)

**Comment by haricane8133** [comment] 2023-12-17 09:25
Yeah. I just found that too. Looking for a regex that can accommodate this...

**Comment by nhandt2021** [comment] 2023-12-17 09:31
> @nhandt2021 What about docker build, does that work ?

@meggarr  It also works for me

![image](https://github.com/conductor-oss/conductor/assets/83625759/3a25e7d3-c577-4f2c-bbaa-7f860cdd4100)

**Comment by haricane8133** [comment] 2023-12-17 10:12
@nhandt2021, there are two parts here
1. react-scripts needs to know the correct path to JS and CSS, to be set inside the generated HTML.
2. Router needs to know how to handle in-browser navigation
3. ... (check this issue for more details - https://github.com/Netflix/conductor/issues/3656)

So, setting `homepage` inside `package.json` is the easiest way, as that field is anyway required by `react-scripts` to set the paths to JS and CSS inside the generated HTML. My changes would reuse the same variable for other places where the change must come in (like router, NavLink, etc)

**Comment by haricane8133** [comment] 2023-12-17 10:26
1. There is an issue with `newTab` navigation as @meggarr mentioned, and the issue is related to the regex not catching multiple slashes at the start of the string.
2. We also need the `+ '/' +` I added as a part of [my PR](https://github.com/Netflix/conductor/pull/3722/files#diff-c868321113245d9cb0c0ed91ae213c8a2b0be4f4ae257aefcef39bee60292c7eR29). The reason for that is, the `homepage` field can either contain a trailing `/`, or NOT. This was removed with [this PR](https://github.com/Netflix/conductor/pull/3873/files#diff-c868321113245d9cb0c0ed91ae213c8a2b0be4f4ae257aefcef39bee60292c7eL29-R29).


Here is a PR with both the changes - https://github.com/conductor-oss/conductor/pull/9

@nhandt2021, let us have @meggarr test the changes and then go for merge...
CC: @v1r3n

**Comment by meggarr** [comment] 2023-12-17 10:32
> @meggarr It also works for me
Can you let me know how to build the docker ? @nhandt2021

**Comment by nhandt2021** [comment] 2023-12-17 11:04
@meggarr I followed this instruction: https://github.com/conductor-oss/conductor/tree/main/docker/ui#running-the-conductor-server

**Comment by meggarr** [comment] 2023-12-17 13:08
I followed the steps in here :: https://github.com/orkes-io/orkes-conductor-community/blob/main/docker/DockerfileServer . Started the server via docker compose. But, now I have tore down my env.

You can give it a try. @nhandt2021

**Comment by haricane8133** [comment] 2023-12-17 13:49
@meggarr, try on top of the PR I've raised.... #9

**Comment by nhandt2021** [comment] 2023-12-17 14:01
@meggarr You'r right. I can't run (UI) with that docker compose 😢

**Comment by haricane8133** [comment] 2023-12-18 02:34
> @meggarr, try on top of the PR I've raised.... #9

Any updates?
@meggarr, @nhandt2021, @v1r3n

Just pinging the way to reproduce the error, in case we went off track with trying docker, etc...

1. Clone the repo
2. Add a temporary `NavLink` in `app.js`, passing the `newTab` param as `true` (we want the link to open in a new tab), and set the `href` as `/temp`
4. `yarn build`
5. `yarn serve-build`
6. Click on that NavLink you added.

* The link should fail if you didn't add any HomePage field (default '/' is taken, and because `cleanDuplicateSlash()` ignores // at the start of the string, we would have the resolved URL as `//temp`, which would open a new tab with the URL `http://temp`)
* The link should pass if you set some homepage field.


Now the PR fixes the regex, and the `newTab` link should work with the default homepage value.

**Comment by nhandt2021** [comment] 2023-12-18 02:39
@haricane8133 
Have you tried with this case:

> I followed the steps in here :: https://github.com/orkes-io/orkes-conductor-community/blob/main/docker/DockerfileServer . Started the server via docker compose. But, now I have tore down my env.

**Comment by haricane8133** [comment] 2023-12-18 02:48
@nhandt2021,

No I haven't. Why is that needed?
We are trying to test a bug that is related to Navigation within the UI.

You just need to try both
1. DevServer - `yarn start`
2. ProductionBuild - `yarn build` + `yarn serve-build`

(actually considering the bug, one of them should be good enough too)

But the testing should cover all scenarios related to the different ways one can have the `homepage` field, and different ways one can pass path to the `NavLink`.

**Comment by nhandt2021** [comment] 2023-12-18 03:22
@haricane8133 @meggarr 
The problem I still couldn't run that docker compose even I reverted the change 🤔

**Comment by haricane8133** [comment] 2023-12-19 04:40
> @haricane8133 Could you run the index.html directly after building? (I can't even revert the change)

This would be the same as `yarn serve-build`. Yeah. I did that on top of my PR, and it fixes this issue

**Comment by meggarr** [comment] 2023-12-22 09:00
Shall we revert changes if it is still not good ?

**Comment by haricane8133** [comment] 2023-12-22 09:32
@meggarr, you should let us know...

The PR I have mentioned here, #9, fixes this issue (#7). As I had mentioned before, that PR can be merged and this issue closed....

Test it and update here

I am not from Orkes and don't have merge permissions...

Someone from Orkes can merge this PR

**Comment by nhandt2021** [comment] 2023-12-22 09:46
> @haricane8133 @meggarr The problem is I still couldn't run that docker compose even I reverted the change 🤔
> 
> @haricane8133 Could you run the index.html directly after building? (I can't even revert the change)

I'd tested after reverted. And didn't work with the docker compose that you mentioned.
@haricane8133 I tested your PR and it couldn't run the index.html directly (inside build folder) same as revert version

**Comment by haricane8133** [comment] 2023-12-22 12:18
> @haricane8133 I tested your PR and it couldn't run the index.html directly (inside build folder) same as reverted version
> 
> 

@nhandt2021, I am not able to follow. What do you mean by the PR unable to run the `index.html` directly?

Did you run any command scripts from `package.json`? You need to run those commands to run the web application.

You need to either build and serve the static files using any server, or use the in built NodeJS Dev Server....

(By the way, to test the UI, you don't have to run the whole conductor repo. Just focus inside the 'ui' folder)

**Comment by meggarr** [comment] 2023-12-25 02:22
@haricane8133 I am not from Orkes, so I cannot decide here.
In the meantime, can you pls build Docker Image and try, Docker file is here ::  https://github.com/orkes-io/orkes-conductor-community/blob/main/docker/DockerfileServer, it doesn't have the "yarn serve-build"

I don't know how to resolve this, maybe it needs a solution. Cc @nhandt2021

**Comment by nhandt2021** [comment] 2023-12-25 02:57
I don't want to modify the Docker file. I'm finding the the root cause of  this

@haricane8133 about your feature, I believe that doesn't relate with @meggarr issue, because he want to run the whole app via docker containers (https://github.com/orkes-io/orkes-conductor-community/blob/main/docker/DockerfileServer)
And I reverted the old version it still didn't work too. That are all my tests.

Btw: Your pr looks good to me. But I prefer using 1 regex instead replace 2 times with 2 regular expressions

(By the way, to test the UI, you don't have to run the whole conductor repo. Just focus inside the 'ui' folder)
I think have many people don't care to run UI only. Most of them run the app via Docker.

> @haricane8133 I tested your PR and it couldn't run the index.html directly (inside build folder) same as reverted version

I know how to run UI only, and having several way to do that.
And I can't run the index.html inside `build` folder in `ui` folder directly. And one more time I believe it doesn't relate  to your PRs.

Look at this, it runs UI as a static page via Nginx. So the problem here is: if we can't run the static page after build so Docker file either.
<img width="870" alt="image" src="https://github.com/conductor-oss/conductor/assets/83625759/e21b1f05-b23f-469a-8aea-05a46863e137">

**Comment by haricane8133** [comment] 2023-12-25 07:16
@meggarr, @nhandt2021, I can certainly try running the Docker file and let you know. I will update the thread.

> it doesn't have the "yarn serve-build"
@meggarr, we don't have to use `yarn serve-build` compulsorily. You can use any static file server like nginx, or simply [Python's Simple HTTP Server](https://www.digitalocean.com/community/tutorials/python-simplehttpserver-http-server). It will work.

> I know how to run UI only, and having several ways to do that.
> And I can't run the index.html inside `build` folder in `ui` folder directly.
@nhandt2021, I am still not able to understand what you mean by this. Please be more specific. Did you double click the `index.html` file?
After you build the UI react application (within `/ui`), all you have to do is to navigate into the `build` folder and run any static file server on top. Please make sure that you run the server from the correct directory. If you are having an issue, it would mostly be because the relative paths are not working fine. Either way, we would need details more than "I am unable to run the index.html file" to find out what...



> I think have many people don't care to run UI only. Most of them run the app via Docker.
@nhandt2021, it doesn't matter for this issue. If the dockerfile isn't working, let us open another issue and solve it there.
What I am not able to understand is that @meggarr was once able to run the UI application properly to figure out the bug, but is unable to test after the fix is in...?


> Btw: Your pr looks good to me. But I prefer using 1 regex instead of using `replace` 2 times with 2 regular expressions
@nhandt2021, let us continue the discussion on the PR. As I mentioned in the PR, I feel having two `.replace()` at this point would retain code readability standards. But I am fine to change here. Let me know if you can find a regex that can cover both. I wasn't able to find one.

**Comment by meggarr** [comment] 2024-01-07 14:15
@nhandt2021 Is there a direction of this issue ?

**Comment by nhandt2021** [comment] 2024-01-08 02:22
@meggarr As I told you before, I reverted and tried with that docker compose file, but it didn't work too. But you said it worked before, so I was confused.
It works perfectly with the current docker files in this OSS repository.

May I have a question: Do you want to use this `Basename feature` with this docker compose file: https://github.com/orkes-io/orkes-conductor-community/blob/main/docker/DockerfileServer ?

**Comment by meggarr** [comment] 2024-01-08 05:26
@nhandt2021 I didn't revert, I use the version of 3.15.0, it works well.

For the 2nd question - No, I don't use the `"basename feature"`, and I don't want that to break the Docker build for UI.

I think we need a decision here to revert this feature totally, or to keep it in future release. Thanks!

Cc @v1r3n @c4lm

**Closed** 2024-01-09 04:51 UTC
